name: gan2splat
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  - pytorch=2.3
  - cudatoolkit=11.8
  - pytorch-cuda=11.8

  - numpy<2
  - opencv=4.9
  - pillow=10.3
  - plyfile=1.0
  - requests=2.31
  - scikit-image=0.24
  - scipy=1.13
  - tqdm=4.66

  - pip:
    - gaussian_splatting/submodules/diff-gaussian-rasterization
    - gaussian_splatting/submodules/simple-knn
